services:
  gateway:
    image: dairoot/grok-gateway:latest
    ports:
      - "50005:8080"
    restart: always
    volumes:
      - ./.cache_data:/app/.cache_data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - .env
      
  cf5s:
    image: dairoot/cf5s:latest
    depends_on:
      - gateway
    environment:
      - GATEWAY_URL=http://gateway:8080


  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 3600 --label-enable


